
{{- range $key, $definition := .Values.nfs }}
---
# PVC {{ print $key }}-claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$definition.pvcname}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{$definition.storage}}
  volumeName: {{$definition.pvname}}
  storageClassName: "openebs-kernel-nfs"
{{- end }}
